### ISSUE TITLE
ModuleNotFoundError: No module named 'MWUtil'

### ISSUE THREAD

**Issue by snijesh** [metabolomicsworkbench/binder#4]
I was running `MWPerformDataNormalization.ipynb`. It has thrown me an error as
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 19
     16 from IPython import __version__ as ipyVersion
     18 # Import MW modules from the current directory or default Python directory...
---> 19 import MWUtil
     21 get_ipython().run_line_magic('matplotlib', 'inline')
     23 print("Python: %s.%s.%s" % sys.version_info[:3])

ModuleNotFoundError: No module named 'MWUtil'
```

I tried to install `MWUtil` using `pip install MWUtil`:
```
ERROR: Could not find a version that satisfies the requirement MWUtil (from versions: none)
ERROR: No matching distribution found for MWUtil
```

**Comment by kevincoakley** [comment]
Did you clone the whole repository or did you just download the notebook? MWUtil should be a subdirectory in the repository and needs to be downloaded and saved in the same directory as the notebook. I recommend cloning the repository.

**Comment by kevincoakley** [comment]
Sorry, I meant you need to have the MWUtil.py file in the same directory as the notebook file. I still recommend cloning the repository.

**Comment by kevincoakley** [comment]
I am closing the issue, please feel free to open it again if you have additional questions.
